# [START jobmonitor-startup-freelancer_deployment]
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jobmonitor-startup-freelancer
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: jobmonitor-startup-freelancer-app
    spec:
      containers:
      - name: jobmonitor-startup-freelancer-cont
        image: eu.gcr.io/alert-shape-852/startup-jobmonitor-freelancer:latest
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.05"
# [END jobmonitor-startup-freelancer_deployment]
