mongo:
  host: mongodb-service
  port: 27017
  db: jobmonitor
  user: jobmonitorUser
  password: ""

activemq:
  host: activemq-service
  port: 61616
  user: ""
  password: ""
  tasksQueuePrefix: task-

taskManager:
  createTasksInterval: 60
  createTasksCron: 0 * * * * ?
